# Generated by Django 5.2 on 2025-05-23 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_devicesession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicesession",
            old_name="expires_at",
            new_name="expiration_date",
        ),
        migrations.AlterUniqueTogether(
            name="devicesession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="devicesession",
            name="device_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devicesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
