# Generated by Django 5.2.1 on 2025-05-30 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_imageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
